#1

In [ ]:
import copy
import numpy as np
import random


In [ ]:
def understanding(p_size):
   return np.random.choice([0, 1], size=p_size)


In [ ]:
def question (p_size,q_size) :
    return np.random.choice([0, 1], size=(p_size,q_size))


In [ ]:
def importance(q_size):
   importance = np.random.uniform(0, 1, q_size)
   importance /= importance.sum()
   return importance

In [ ]:
weight =importance(10)

In [ ]:
stuednets=np.random.uniform(0, 10, (9,4))

In [ ]:
textbook=np.random.uniform(0, 10, 4)

In [ ]:
mean_ablity=np.mean(stuednets,axis=1)

In [ ]:
diff=(mean_ablity[0]-textbook)/10

In [ ]:
def self_check_indival(diff):
   l=[]
   for i in diff:
     if(i<=0):
        l.append(0)
     else:
        l.append(np.random.choice([0, 1]))
   return  np.array(l)

In [ ]:
def self_check_total(students):
   l=[]
   mean_ablity=np.mean(students,axis=1)
   for i in mean_ablity:
     diff=(i-textbook)/10
     ll=self_check_indival(diff)
     l.append(ll)
   return np.array(l)


In [ ]:
sel_c=self_check_total(stuednets)

In [ ]:
sel_c

array([[0, 1, 0, 0],
       [0, 1, 0, 1],
       [0, 1, 1, 0],
       [1, 1, 0, 0],
       [0, 0, 1, 1],
       [1, 1, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
def question_anser_indival(diff,q_size):
  if(diff<=0):
     p=max(0,0.5+diff)
     return np.random.choice([0,1],q_size,p=[1-p,p])
  p=min(1,0.5+diff)
  return  np.random.choice([0,1],q_size,p=[1-p,p])

In [ ]:
def question_anser_total(mean_ablity, q_size):
    l = []
    for i in range(len(mean_ablity)):  # Iterate using index
        diff = (mean_ablity[i] - textbook) / 10  # Calculate diff for each student
        ll = []
        for j in range(len(diff)):  # Iterate through each subject
            ll.append(question_anser_indival(diff[j], q_size))  # Pass single diff value
        l.append(np.array(ll))
    return np.array(l)


In [ ]:
mean_ablity

array([4.777561  , 5.72139814, 4.18744747, 4.98770747])

In [ ]:
ll=question_anser_total(mean_ablity,10)

In [ ]:
weight =importance(10)

In [ ]:
def fittness_func(prior,question_anser,question_importance,students):
     return prior*0.1+0.45*(question_anser@question_importance)+0.45*(stuednets/10)

In [ ]:
def fittness_func(prior,question_anser,question_importance,students):
     fittness=prior*0.35+0.5*(question_anser@question_importance)+0.15*(stuednets/10)
     k=np.exp(-np.abs(sel_c-np.sum(ll,axis=2)/10)*stuednets)
     fitness=fittness*k
     return fittness


In [ ]:
fittness=fittness_func(sel_c,ll,weight,stuednets)

In [ ]:
posterior = prior*likelihoods

In [ ]:
def selection(students,textbbok,fitness):
  diff=stuednets-textbook.reshape(1,-1)
  prior=np.exp(-0.5*(diff/np.std(diff))**2)
  likelihoods=np.exp(-0.1*fitness)
  posterior = prior*likelihoods
  posterior=(posterior)/np.sum(posterior,axis=1).reshape(-1,1)

  return np.argmax(posterior,axis=1)

In [ ]:
sele=selection(stuednets,textbook,fittness)

In [ ]:
sele

array([2, 2, 1, 0, 3, 2, 2, 0, 3])

In [ ]:
study_gain=ll[np.arange(len(stuednets)),sele,]

array([[1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 1, 0, 1, 1, 1],
       [0, 1, 1, 1, 1, 1, 1, 0, 1, 1],
       [0, 0, 0, 1, 0, 0, 0, 1, 1, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 0, 1, 1, 0, 0, 1, 1, 1],
       [1, 0, 1, 1, 1, 1, 0, 0, 1, 1],
       [1, 1, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 1, 1, 0, 0, 1, 1]])

In [ ]:
study_gain=ll[np.arange(9),np.argmax(fittness,axis=1) ,]

In [ ]:
prior=np.exp(-0.5*(diff/np.std(diff))**2)

In [ ]:
likelihoods=np.exp(-0.1*fittness)

In [ ]:
diff=stuednets-textbook.reshape(1,-1)

In [ ]:
np.exp(-0.5*(diff/np.std(diff))**2)

array([[0.43764733, 0.61879465, 0.76646379, 0.4504844 ],
       [0.44836465, 0.13521462, 0.99321515, 0.6757517 ],
       [0.42452454, 0.99759716, 0.65442333, 0.42064022],
       [0.58444934, 0.38233249, 0.43273538, 0.11659862],
       [0.84787931, 0.66163893, 0.56136262, 0.95755435],
       [0.97223384, 0.53260504, 0.98845379, 0.25711597],
       [0.86934024, 0.63477803, 0.98279282, 0.12418088],
       [0.87190213, 0.1486452 , 0.64115305, 0.38742563],
       [0.70523826, 0.94938828, 0.65317162, 0.9802733 ]])

In [ ]:
weight=importance(4)

In [ ]:
def update_ablity_peronal(students,textbook,weight,study_gain):
    delta=((1-(stuednets-textbook)*weight)*(np.sum(study_gain,axis=1).reshape(-1,1))/10)*1.5
    delta=np.where(delta>=10, 10)
    return students+delta

In [ ]:
def crossover_personal(student1,student2,weight,mean):
    return weight[0]*student1+weight[1]*student2+weight[2]*mean




In [ ]:
weight1=importance(3)

In [ ]:
def crossover_total(students,mean,weight):
       crossover_count = np.random.randint(1,8)

       for _ in range(crossover_count):
           parent=np.random.choice(range(len(students)),2)
           students[parent[0]]=crossover_personal(students[parent[0]],students[parent[1]],weight,mean)
           students[parent[1]]=crossover_personal(students[parent[1]],students[parent[0]],weight,mean)
       return students


In [ ]:
parent=np.random.choice(range(len(stuednets)),2)

In [ ]:
mean=np.mean(stuednets,axis=0)

In [ ]:
crossover_personal(stuednets[parent[0]],stuednets[parent[1]],weight1,mean)

array([5.9042428 , 4.49656151, 5.7677217 , 6.75047868])

In [ ]:
mean_ablity=np.mean(stuednets,axis=0)

In [ ]:
divi=(stuednets[0] -mean_ablity)

In [ ]:
0.5*np.exp(-0.1*(np.abs((stuednets[0] -mean_ablity))+np.random.normal(0,0.5)))*(stuednets[0] -mean_ablity)

array([-1.01680506, -1.53328923,  0.42154946,  0.09520772])

In [ ]:
noise=np.random.normal(0,0.5*np.abs(divi))

In [ ]:
np.exp(-0.1*(np.abs(divi)+noise))*divi

array([-1.93912154, -3.68109186,  0.7805472 ,  0.18716572])

In [ ]:
def mutation_person(student,text_book):
    divi=(student -text_book)
    mutation_prob = 0.2* np.exp(-0.1 * np.abs(divi))
    if np.random.random() < mutation_prob:
        student+=np.random.normal(0,1)
    if  np.random.random() < mutation_prob:
        student-=np.random.normal(0,1)

    noise=np.random.normal(0,0.5*np.abs(divi))
    student+=np.exp(-0.1*(np.abs(divi)+noise))*divi
    student = np.clip(student, 0, 10)
    return student



In [ ]:
def mutation_total(students,text_book):
    for i in range(len(students)):
        students[i]=mutation_person(students[i],text_book)
    return students

#2

In [ ]:
import copy
import numpy as np
import random
def importance(q_size):
   importance = np.random.uniform(0, 1, q_size)
   importance /= importance.sum()
   return importance
def self_check_indival(diff):
   l=[]
   for i in diff:
     if(i<=0):
        l.append(0)
     else:
        l.append(np.random.choice([0, 1]))
   return  np.array(l)
def self_check_total(students):
   l=[]
   mean_ablity=np.mean(students,axis=1)
   for i in mean_ablity:
     diff=(i-textbook)/10
     ll=self_check_indival(diff)
     l.append(ll)
   return np.array(l)

def question_anser_indival(diff,q_size):
  if(diff<=0):
     p=max(0,0.5+diff)
     return np.random.choice([0,1],q_size,p=[1-p,p])
  p=min(1,0.5+diff)
  return  np.random.choice([0,1],q_size,p=[1-p,p])

def question_anser_total(mean_ablity, q_size):
    l = []
    for i in range(len(mean_ablity)):  # Iterate using index
        diff = (mean_ablity[i] - textbook) / 10  # Calculate diff for each student
        ll = []
        for j in range(len(diff)):  # Iterate through each subject
            ll.append(question_anser_indival(diff[j], q_size))  # Pass single diff value
        l.append(np.array(ll))
    return np.array(l)

def fittness_func(prior,question_anser,question_importance,students):
     fittness=prior*0.35+0.5*(question_anser@question_importance)+0.15*(students/10)
     k=np.exp(-np.abs(prior-np.sum(question_anser,axis=2)/10)*students)
     fitness=fittness*k
     return fittness

def selection(students,textbbok,fitness):
  diff=students-textbook.reshape(1,-1)
  prior=np.exp(-0.5*(diff/np.std(diff))**2)
  likelihoods=np.exp(-0.1*fitness)
  posterior = prior*likelihoods
  posterior=(posterior)/np.sum(posterior,axis=1).reshape(-1,1)

  return np.argmax(posterior,axis=1)

def update_ablity_peronal(students,textbook,weight,study_gain):
    delta=((1-(students-textbook)*weight)*(np.sum(study_gain,axis=1).reshape(-1,1))/10)*1.5
    delta=np.where(delta>=10, 10,delta)
    return students+delta


def crossover_personal(student1,student2,weight,mean):
    return weight[0]*student1+weight[1]*student2+weight[2]*mean
def crossover_total(students,mean,weight):
       crossover_count = np.random.randint(1,8)

       for _ in range(crossover_count):
           parent=np.random.choice(range(len(students)),2)
           students[parent[0]]=crossover_personal(students[parent[0]],students[parent[1]],weight,mean)
           students[parent[1]]=crossover_personal(students[parent[1]],students[parent[0]],weight,mean)
       return students


def mutation_person(student,text_book):
    divi=(student -text_book)
    mutation_prob = 0.2* np.exp(-0.1 * np.abs(divi))
    if (np.random.random() < mutation_prob).any():
        student+=np.random.normal(0,1)
    if  (np.random.random() < mutation_prob).any():
        student-=np.random.normal(0,1)

    noise=np.random.normal(0,0.5*np.abs(divi))
    student+=np.exp(-0.1*(np.abs(divi)+noise))*divi
    #student = np.clip(student, 0, 10)
    student=np.clip(student, 0, 10)
    return student

def mutation_total(students,text_book):
    for i in range(len(students)):
        students[i]=mutation_person(students[i],text_book)
    return students


def data_generation(students,size):
      mean_ablity=np.mean(students,axis=1)
      self_check=self_check_total(students)
      question_anser=question_anser_total(mean_ablity,size)
      return mean_ablity, self_check,question_anser
def print_chosen_result(selected_index):
    for i in range(len(selected_index)):
       print("学生"+"no"+str(i)+" "+"にno"+str(selected_index[i])+ "の本が"+"が選ばれました。")

def print_final_result(students):
     for i in range(len(students)):
        print(students[i])


def ga(students,textbook,generation):
  for i in range(generation):
        print(str(i + 1) + u"世代")
        mean_ablity, self_check,question_anser=data_generation(students,10)


        fitness=fittness_func(self_check,question_anser,importance(10),students)
        selected_index=selection(students,textbook,fitness)
        print_chosen_result(selected_index)
        study_gain=question_anser[np.arange(len(students)),selected_index,]
        up_students=update_ablity_peronal(students,textbook,importance(4),study_gain)

        cross_students=crossover_total(students,np.mean(students,axis=0),importance(3))
        mutated_students=mutation_total(cross_students,textbook)

        print_final_result(mutated_students)

def main():
    students=np.random.uniform(0, 10, (9,4))
    textbook=np.random.uniform(0, 10, 4)
    ga(students,textbook,10)

if __name__ == "__main__":
    main()

1世代
学生no0 にno1の本がが選ばれました。
学生no1 にno0の本がが選ばれました。
学生no2 にno1の本がが選ばれました。
学生no3 にno0の本がが選ばれました。
学生no4 にno1の本がが選ばれました。
学生no5 にno2の本がが選ばれました。
学生no6 にno2の本がが選ばれました。
学生no7 にno3の本がが選ばれました。
学生no8 にno0の本がが選ばれました。
[6.96150014 9.198374   3.61038434 1.88962596]
[7.88534247 5.04362152 1.50732504 2.65470556]
[ 0.         10.          3.92593289  0.        ]
[8.59449594 4.45749929 1.25694115 2.66787899]
[6.82295949 9.35654347 2.77300665 1.92306951]
[7.1145208  4.95164114 6.43580032 5.10258056]
[3.49261471 3.35988187 0.         0.68174481]
[4.66937852 4.04430572 1.17039401 1.56503414]
[4.8936893  5.09919988 1.18201897 2.04348851]
2世代
学生no0 にno0の本がが選ばれました。
学生no1 にno0の本がが選ばれました。
学生no2 にno2の本がが選ばれました。
学生no3 にno3の本がが選ばれました。
学生no4 にno1の本がが選ばれました。
学生no5 にno0の本がが選ばれました。
学生no6 にno3の本がが選ばれました。
学生no7 にno3の本がが選ばれました。
学生no8 にno3の本がが選ばれました。
[10.         10.          2.04099696  0.64481733]
[8.9867664  5.36770118 0.         0.        ]
[ 0.         10.          1.32632016  0.        ]
[10.          3.23863341  0.    

In [ ]:
import copy
import numpy as np
import random


In [ ]:
def importance(q_size):
   importance = np.random.uniform(0, 1, q_size)
   importance /= importance.sum()
   return importance

In [ ]:
def self_check_indival(diff):
   l=[]
   for i in diff:
     if(i<=0):
        l.append(0)
     else:
        l.append(np.random.choice([0, 1]))
   return  np.array(l)
def self_check_total(students):
   l=[]
   mean_ablity=np.mean(students,axis=1)
   for i in mean_ablity:
     diff=(i-textbook)/10
     ll=self_check_indival(diff)
     l.append(ll)
   return np.array(l)



In [ ]:
def question_anser_indival(diff,q_size):
  if(diff<=0):
     p=max(0,0.5+diff)
     return np.random.choice([0,1],q_size,p=[1-p,p])
  p=min(1,0.5+diff)
  return  np.random.choice([0,1],q_size,p=[1-p,p])

def question_anser_total(mean_ablity, q_size):
    l = []
    for i in range(len(mean_ablity)):  # Iterate using index
        diff = (mean_ablity[i] - textbook) / 10  # Calculate diff for each student
        ll = []
        for j in range(len(diff)):  # Iterate through each subject
            ll.append(question_anser_indival(diff[j], q_size))  # Pass single diff value
        l.append(np.array(ll))
    return np.array(l)

In [ ]:
def fittness_func(prior,question_anser,question_importance,students):
     fittness=prior*0.35+0.5*(question_anser@question_importance)+0.15*(students/10)
     k=np.exp(-np.abs(sel_c-np.sum(question_anser,axis=2)/10)*students)
     fitness=fittness*k
     return fittness

def selection(students,textbbok,fitness):
  diff=students-textbook.reshape(1,-1)
  prior=np.exp(-0.5*(diff/np.std(diff))**2)
  likelihoods=np.exp(-0.1*fitness)
  posterior = prior*likelihoods
  posterior=(posterior)/np.sum(posterior,axis=1).reshape(-1,1)

  return np.argmax(posterior,axis=1)

In [ ]:
def update_ablity_peronal(students,textbook,weight,study_gain):
    delta=((1-(students-textbook)*weight)*(np.sum(study_gain,axis=1).reshape(-1,1))/10)*1.5
    delta=np.where(delta>=10, 10,delta)
    return students+delta

In [ ]:
def crossover_personal(student1,student2,weight,mean):
    return weight[0]*student1+weight[1]*student2+weight[2]*mean
def crossover_total(students,mean,weight):
       crossover_count = np.random.randint(1,8)

       for _ in range(crossover_count):
           parent=np.random.choice(range(len(students)),2)
           students[parent[0]]=crossover_personal(students[parent[0]],students[parent[1]],weight,mean)
           students[parent[1]]=crossover_personal(students[parent[1]],students[parent[0]],weight,mean)
       return students

In [ ]:
def mutation_person(student,text_book):
    divi=(student -text_book)
    mutation_prob = 0.2* np.exp(-0.1 * np.abs(divi))
    if (np.random.random() < mutation_prob).any():
        student+=np.random.normal(0,1)
    if  (np.random.random() < mutation_prob).any():
        student-=np.random.normal(0,1)

    noise=np.random.normal(0,0.5*np.abs(divi))
    student+=np.exp(-0.1*(np.abs(divi)+noise))*divi
    student = np.clip(student, 0, 10)
    return student

def mutation_total(students,text_book):
    for i in range(len(students)):
        students[i]=mutation_person(students[i],text_book)
    return students

In [ ]:
def data_generation(students,size):
      mean_ablity=np.mean(students,axis=1)
      self_check=self_check_total(students)
      question_anser=question_anser_total(mean_ablity,size)
      return mean_ablity, self_check,question_anser
def print_chosen_result(selected_index):
    for i in range(len(selected_index)):
       print("学生"+"no"+str(i)+" "+"にno"+str(selected_index[i])+ "の本が"+"が選ばれました。")

def print_final_result(students):
     for i in range(len(students)):
        print(students[i])

In [ ]:
def ga(students,textbook,generation):
  for i in range(generation):
        print(str(i + 1) + u"世代")
        mean_ablity, self_check,question_anser=data_generation(students,10)


        fitness=fittness_func(self_check,question_anser,importance(10),students)
        selected_index=selection(students,textbook,fitness)
        print_chosen_result(selected_index)
        study_gain=question_anser[np.arange(len(students)),selected_index,]
        up_students=update_ablity_peronal(students,textbook,importance(4),study_gain)

        cross_students=crossover_total(students,np.mean(students,axis=0),importance(3))
        mutated_students=mutation_total(cross_students,textbook)

        print_final_result(mutated_students)









In [ ]:
def main():
    students=np.random.uniform(0, 10, (9,4))
    textbook=np.random.uniform(0, 10, 4)
    ga(students,textbook,10)

In [ ]:
if __name__ == "__main__":
    main()

1世代
学生no0 にno2の本がが選ばれました。
学生no1 にno3の本がが選ばれました。
学生no2 にno0の本がが選ばれました。
学生no3 にno2の本がが選ばれました。
学生no4 にno0の本がが選ばれました。
学生no5 にno3の本がが選ばれました。
学生no6 にno2の本がが選ばれました。
学生no7 にno3の本がが選ばれました。
学生no8 にno1の本がが選ばれました。
[1.85853831 5.3590382  5.55320479 7.67301413]
[5.25701567 0.         7.33991262 0.        ]
[10.          0.49907457  0.          4.96045017]
[1.8066657  2.79878741 0.         5.03245871]
[10.          1.18314682  9.40693807  3.61884621]
[6.59925682 0.26474532 8.46917029 0.        ]
[6.22931501 0.         0.17215591 5.33491518]
[10.          7.34544449 10.          2.66770913]
[ 9.44991805 10.          9.79909512  0.        ]
2世代
学生no0 にno2の本がが選ばれました。
学生no1 にno0の本がが選ばれました。
学生no2 にno3の本がが選ばれました。
学生no3 にno3の本がが選ばれました。
学生no4 にno3の本がが選ばれました。
学生no5 にno0の本がが選ばれました。
学生no6 にno0の本がが選ばれました。
学生no7 にno3の本がが選ばれました。
学生no8 にno1の本がが選ばれました。
[0.59755918 5.71674302 4.2867629  5.20565146]
[9.20133998 1.67264242 6.40107949 0.        ]
[9.8427224  2.96379983 5.32415375 0.24017016]
[9.43188098 2.74069261 4.327